ENT.Base 			= "npc_vj_con_zfemale"
ENT.Type 			= "ai"
ENT.PrintName 		= "Jessica (Zombie)"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Contagion"